function automated_email_v5(concat_data)

% parameters
mail = 'info@busscos.com'; % my gmail address
password = 'ojhrhydygibyfmrr';  % my gmail password
host = 'smtp.gmail.com';

Subject = 'Your BCOS Commute Recommendations are Ready!';


setpref('Internet','E_mail',mail);
setpref('Internet','SMTP_Server','smtp.gmail.com');
setpref('Internet','SMTP_Username',mail);
setpref('Internet','SMTP_Password',password);
% Gmail server.
props = java.lang.System.getProperties;
props.setProperty('mail.smtp.auth','true');
props.setProperty('mail.smtp.socketFactory.class', 'javax.net.ssl.SSLSocketFactory');
props.setProperty('mail.smtp.socketFactory.port','465');


for it_com = 2:size(concat_data,1)

    first_name = extractBefore(concat_data{it_com,2},' ') ;

    email_txt_to_users = {sprintf('%s',first_name),...
        '',...
        'Thank you for signing up for the Denver BCOS Pilot.', ...
        '',...
        'Your commute recommendations for next week are ready! Please log on to BCOS (https://www.commuteopt.com/login) and click on the “Recommended Commute Plans” tab to review them and see what works for you. Your commute recommendations may include walking, biking, transit, driving or potential carpool matches. You can start following recommendations on Tuesday.',...
        '',...
        'Don’t like the recommendations? If you decline your commute options, or if you want to update your commute survey for next week please do so by Thursday.' , ...
        '',...
        'Don’t forget to log your trips! At the end of the week log your trips to calculate your footprint on the self report tab. It’ll just take 1-2 minutes!' ,...
        '',...
        'Rewards you can win! You can win up to $130 in rewards for participation in this challenge! Check out all the rewards on the challenge website: https://www.commutemetrics.com/doti',...
        '',...
        'If you have any questions or issues please contact Project Manager Nora Kern: info@busscos.com.',...
        '',...
        'Happy Commuting!',...
        '-BCOS Team',...
        '',...
        '',...
        '** Note: data collected in the BCOS pilot will be private, only anonymized (no personally identifiable) data will be used in generating emission reports to the city.'} ;

    % sendto = {'shahryar.monghasemi@gmail.com'};
    % sendto = {'moatassem.abdallah@ucdenver.edu'};
    % sendto = {'engmoatassem83@gmail.com'};
    sendto = {concat_data(it_com,3)};

    % send email with attachment to recipients
    sendmail(sendto, Subject, email_txt_to_users)
end
