function DowntownDenverCommuterSurveyOctober = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DOWNTOWNDENVERCOMMUTERSURVEYOCTOBER25202217S2 = IMPORTFILE(FILE)
%  reads data from the first worksheet in the Microsoft Excel
%  spreadsheet file named FILE.  Returns the data as a string array.
%
%  DOWNTOWNDENVERCOMMUTERSURVEYOCTOBER25202217S2 = IMPORTFILE(FILE,
%  SHEET) reads from the specified worksheet.
%
%  DOWNTOWNDENVERCOMMUTERSURVEYOCTOBER25202217S2 = IMPORTFILE(FILE,
%  SHEET, DATALINES) reads from the specified worksheet for the
%  specified row interval(s). Specify DATALINES as a positive scalar
%  integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  DowntownDenverCommuterSurveyOctober25202217S2 = importfile("/Users/shahryarmonghasemi/MATLAB-Drive/Commuter Survey Analysis/Downtown Denver Commuter Survey_October 25, 2022_17.12- Choice Text.xlsx", "Addresses", [3, 4558]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 01-Nov-2022 18:34:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 3668];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Q2_6", "Q2_8", "Q6_4", "Q6_5", "Q5_1", "Q7"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Q2_6", "Q2_8", "Q6_4", "Q6_5", "Q5_1", "Q7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Q2_6", "Q2_8", "Q6_4", "Q6_5", "Q5_1", "Q7"], "EmptyFieldRule", "auto");

% Import the data
DowntownDenverCommuterSurveyOctober = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    DowntownDenverCommuterSurveyOctober = [DowntownDenverCommuterSurveyOctober; tb]; %#ok<AGROW>
end

end